### ISSUE TITLE
Editing tricks does not store the changes (properly)

### ISSUE THREAD

**Issue by JulianDietzel** [bastislack/highline-freestyle#240] opened 2023-03-13 10:31 UTC
When a predefined trick is edited and then saved, it does not get stored (properly). No error is raised but when clicking on the trick again, the changes do not show up. (Very very occasionally I can manage for the changes to show up, I don't have a clue as to how though)

This is probably a result of the [saveTrick](https://github.com/bastislack/highline-freestyle/blob/b35b5ff5e098e1f1e512950174ed5f2fd12fd147/src/services/db.js#L189) function being used to update the (predefined) trick, whilst actually being designed to store user tricks (at least according to the comment above the function). So the update actually does get stored, but in the `userTricks` table. (Therefore I assume that the issue only occurs for predefined tricks, I could not test this though due to issue #234).

I am not sure if this is done intentionally so as to keep the predefined tricks untouched and store the changes in the `userTricks` table or if this is an oversight.

Also, searching for the error, I noticed that Dexies `put()` function is used in a lot of places where `update()` would be more appropriate (this is probably the reason why tricks get "unboosted" / when the stickFrequency is changed). `put()` overwrites the entire entry instead of just updating the provided fields. Maybe this is related to the issue.

**Comment by weberax** [comment] 2023-08-28 01:37
I could not reproduce this. 
@JulianDietzel is this still a bug?

**Comment by weberax** [comment] 2023-08-28 21:43
I had a deeper look on this and changed some stuff (acfc28fa, 6bc5de8a). Also with the big refactor coming up, I would close this issue for now

**Closed by weberax** 2023-08-28 21:43 UTC
Labels: bug
